<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class Kadad_CMS_License_Manager {
	const OPTION = 'kadad_cms_license';
	public function __construct() {
		add_action( 'admin_init', array( $this, 'migrate_bootstrap_license' ), 1 );
		add_action( 'admin_init', array( $this, 'maybe_validate' ) );
		add_action( 'admin_post_kadad_cms_activate', array( $this, 'handle_activation' ) );
		add_action( 'admin_notices', array( $this, 'license_notice' ) );
		if ( defined( 'WP_INSTALLING' ) && WP_INSTALLING && ! $this->has_bootstrap_license() ) { add_action( 'muplugins_loaded', array( $this, 'gate_installer' ), 1 ); }
	}
	public function migrate_bootstrap_license(): void { if ( get_option( self::OPTION, false ) || ! $this->has_bootstrap_license() ) return; $raw = file_get_contents( WP_CONTENT_DIR . '/.kadad-license.php' ); $json = is_string( $raw ) ? substr( $raw, strpos( $raw, "\n" ) + 1 ) : ''; $data = json_decode( $json, true ); if ( is_array( $data ) && ! empty( $data['code'] ) ) { $license = wp_parse_args( array( 'code' => sanitize_text_field( $data['code'] ), 'active' => true, 'status' => 'active', 'last_validated' => time(), 'checked_at' => time(), 'connection' => 'connected' ), $this->defaults() ); update_option( self::OPTION, $license, false ); } }
	public function defaults(): array { return array( 'api_url' => 'https://wnat.ir/api', 'validation_interval' => DAY_IN_SECONDS, 'grace_period' => 72 * HOUR_IN_SECONDS, 'debug_logging' => false, 'ui_compact' => false ); }
	public function get(): array { return wp_parse_args( get_option( self::OPTION, array() ), $this->defaults() ); }
	public function is_active(): bool { $license = $this->get(); return ! empty( $license['active'] ) && 'active' === ( $license['status'] ?? '' ); }
	public function get_status(): string { return (string) ( $this->get()['status'] ?? 'inactive' ); }
	public function remaining(): array { $license = $this->get(); $expires = (int) ( $license['expires_at'] ?? 0 ); $seconds = $expires ? max( 0, $expires - time() ) : (int) ( $license['remaining_seconds'] ?? 0 ); return array( 'days' => intdiv( $seconds, DAY_IN_SECONDS ), 'hours' => intdiv( $seconds % DAY_IN_SECONDS, HOUR_IN_SECONDS ), 'minutes' => intdiv( $seconds % HOUR_IN_SECONDS, MINUTE_IN_SECONDS ), 'seconds' => $seconds % MINUTE_IN_SECONDS, 'total_seconds' => $seconds, 'expires_at' => $expires ); }
	public function masked_code(): string { $code = (string) ( $this->get()['code'] ?? '' ); return $code ? str_repeat( '•', max( 0, strlen( $code ) - 4 ) ) . substr( $code, -4 ) : '—'; }
	public function gate_installer(): void { wp_safe_redirect( '../license.php' ); exit; }
	private function has_bootstrap_license(): bool { return file_exists( WP_CONTENT_DIR . '/.kadad-license.php' ); }
	public function maybe_validate(): void { if ( ! current_user_can( 'manage_options' ) ) { return; } $l = $this->get(); if ( empty( $l['code'] ) || (int) ( $l['checked_at'] ?? 0 ) + (int) $l['validation_interval'] > time() ) { return; } $this->validate(); }
	public function validate(): array { $l = $this->get(); if ( empty( $l['code'] ) ) { return array( 'ok' => false ); } $client = new CMS_License_Client( $l['api_url'] ); $result = $client->validate( $l['code'] ); $l['checked_at'] = time(); if ( ! empty( $result['ok'] ) ) { $time = $client->get_remaining_time( $l['code'] ); $l['active'] = true; $l['status'] = 'active'; $l['last_validated'] = time(); $l['connection'] = 'connected'; if ( ! empty( $time['remaining'] ) ) { $this->apply_remaining( $l, $time['remaining'] ); } $this->log( 'successful_validation' ); } elseif ( in_array( $result['error'] ?? '', array( 'network', 'remote', 'malformed' ), true ) && (int) ( $l['last_validated'] ?? 0 ) + (int) $l['grace_period'] > time() ) { $l['status'] = 'grace'; $l['connection'] = 'unavailable'; $this->log( 'validation_failed_grace' ); } else { $l['active'] = false; $l['status'] = 'validation_required'; $l['connection'] = 'unavailable'; $this->log( 'validation_failed' ); } update_option( self::OPTION, $l, false ); return $result; }
	private function apply_remaining( array &$license, array $remaining ): void { $seconds = $remaining['days'] * DAY_IN_SECONDS + $remaining['hours'] * HOUR_IN_SECONDS + $remaining['minutes'] * MINUTE_IN_SECONDS + $remaining['seconds']; $license['remaining_seconds'] = $seconds; $license['expires_at'] = ! empty( $remaining['expires_at'] ) ? (int) $remaining['expires_at'] : time() + $seconds; if ( 0 === $seconds ) { $license['active'] = false; $license['status'] = 'expired'; $this->log( 'expired' ); } }
	public function handle_activation(): void { if ( ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'Unauthorized request.', 'kadad-cms' ) ); } check_admin_referer( 'kadad_cms_activate' ); $code = preg_replace( '/[^A-Za-z0-9_-]/', '', (string) wp_unslash( $_POST['subscription_code'] ?? '' ) ); if ( ! $code ) { wp_safe_redirect( add_query_arg( 'kadad_error', 'empty', admin_url( 'admin.php?page=subscription' ) ) ); exit; } $l = $this->get(); $client = new CMS_License_Client( $l['api_url'] ); $result = $client->activate( $code ); if ( empty( $result['ok'] ) ) { $this->log( 'activation_failed' ); wp_safe_redirect( add_query_arg( 'kadad_error', 'invalid', admin_url( 'admin.php?page=subscription' ) ) ); exit; } $l['code'] = $code; $l['active'] = true; $l['status'] = 'active'; $l['last_validated'] = time(); $l['checked_at'] = time(); $l['connection'] = 'connected'; $time = $client->get_remaining_time( $code ); if ( ! empty( $time['remaining'] ) ) { $this->apply_remaining( $l, $time['remaining'] ); } update_option( self::OPTION, $l, false ); $this->log( 'activation' ); wp_safe_redirect( add_query_arg( 'kadad_activated', '1', admin_url( 'admin.php?page=subscription' ) ) ); exit; }
	public function save_settings( array $input ): void { $l = $this->get(); $l['api_url'] = esc_url_raw( $input['api_url'] ?? $l['api_url'] ); $l['validation_interval'] = max( HOUR_IN_SECONDS, absint( $input['validation_interval'] ?? $l['validation_interval'] ) ); $l['grace_period'] = max( HOUR_IN_SECONDS, absint( $input['grace_period'] ?? $l['grace_period'] ) ); $l['debug_logging'] = ! empty( $input['debug_logging'] ); $l['ui_compact'] = ! empty( $input['ui_compact'] ); update_option( self::OPTION, $l, false ); }
	public function log( string $event ): void { $l = $this->get(); if ( empty( $l['debug_logging'] ) ) return; $logs = get_option( 'kadad_cms_license_logs', array() ); $logs[] = array( 'event' => sanitize_key( $event ), 'time' => time() ); update_option( 'kadad_cms_license_logs', array_slice( $logs, -100 ), false ); }
	public function license_notice(): void { if ( current_user_can( 'manage_options' ) && ! $this->is_active() ) echo '<div class="notice notice-warning"><p>' . esc_html__( 'Kadad CMS subscription needs attention. Public website functionality is unaffected.', 'kadad-cms' ) . ' <a href="' . esc_url( admin_url( 'admin.php?page=subscription' ) ) . '">' . esc_html__( 'Manage subscription', 'kadad-cms' ) . '</a></p></div>'; }
}
