<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class Kadad_CMS_Admin {
	private Kadad_CMS_License_Manager $license;
	public function __construct( Kadad_CMS_License_Manager $license ) { $this->license = $license; add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'wp_dashboard_setup', array( $this, 'dashboard_widget' ) ); add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) ); add_action( 'admin_init', array( $this, 'settings' ) ); }
	public function menu(): void { add_menu_page( __( 'Kadad CMS', 'kadad-cms' ), __( 'Kadad CMS', 'kadad-cms' ), 'manage_options', 'subscription', array( $this, 'subscription_page' ), 'dashicons-shield-alt', 3 ); add_submenu_page( 'subscription', __( 'My Subscription', 'kadad-cms' ), __( 'My Subscription', 'kadad-cms' ), 'manage_options', 'subscription', array( $this, 'subscription_page' ) ); add_submenu_page( 'subscription', __( 'CMS Settings', 'kadad-cms' ), __( 'Settings', 'kadad-cms' ), 'manage_options', 'kadad-cms-settings', array( $this, 'settings_page' ) ); }
	public function assets( string $hook ): void { if ( false === strpos( $hook, 'subscription' ) && false === strpos( $hook, 'kadad-cms' ) ) return; wp_enqueue_style( 'kadad-cms-admin', KADAD_CMS_URL . '/admin/css/admin.css', array(), KADAD_CMS_VERSION ); wp_enqueue_script( 'kadad-cms-countdown', KADAD_CMS_URL . '/admin/js/countdown.js', array(), KADAD_CMS_VERSION, true ); wp_localize_script( 'kadad-cms-countdown', 'kadadCms', array( 'endpoint' => esc_url_raw( rest_url( 'cms/v1/subscription' ) ), 'nonce' => wp_create_nonce( 'wp_rest' ) ) ); }
	public function dashboard_widget(): void { wp_add_dashboard_widget( 'kadad_cms_subscription', __( 'Subscription', 'kadad-cms' ), array( $this, 'widget' ) ); }
	public function widget(): void { $r = $this->license->remaining(); $l = $this->license->get(); $active = $this->license->is_active(); echo '<div class="kadad-card"><strong class="kadad-status ' . esc_attr( $active ? 'is-active' : 'is-inactive' ) . '">' . esc_html( $active ? __( 'Active subscription', 'kadad-cms' ) : __( 'Subscription requires attention', 'kadad-cms' ) ) . '</strong><p>' . esc_html( sprintf( __( '%1$d days and %2$d hours remaining', 'kadad-cms' ), $r['days'], $r['hours'] ) ) . '</p><div class="kadad-progress"><span style="width:' . esc_attr( min( 100, $r['days'] > 0 ? 100 : 5 ) ) . '%"></span></div><p><small>' . esc_html__( 'Code:', 'kadad-cms' ) . ' ' . esc_html( $this->license->masked_code() ) . ' · ' . esc_html__( 'Last check:', 'kadad-cms' ) . ' ' . esc_html( ! empty( $l['checked_at'] ) ? wp_date( 'Y-m-d H:i', (int) $l['checked_at'] ) : '—' ) . '</small></p><a class="button" href="' . esc_url( admin_url( 'admin.php?page=subscription' ) ) . '">' . esc_html__( 'Manage subscription', 'kadad-cms' ) . '</a></div>'; }
	public function subscription_page(): void { if ( ! current_user_can( 'manage_options' ) ) wp_die( esc_html__( 'Unauthorized request.', 'kadad-cms' ) ); $r = $this->license->remaining(); $l = $this->license->get(); ?><div class="wrap kadad-wrap"><h1><?php esc_html_e( 'My Subscription', 'kadad-cms' ); ?></h1><?php if ( isset( $_GET['kadad_error'] ) ) : ?><div class="notice notice-error"><p><?php esc_html_e( 'The subscription code could not be activated. Check it and try again.', 'kadad-cms' ); ?></p></div><?php endif; ?><div class="kadad-panel"><span class="kadad-status <?php echo esc_attr( $this->license->is_active() ? 'is-active' : 'is-inactive' ); ?>"><?php echo esc_html( $this->license->get_status() ); ?></span><h2 data-kadad-countdown data-seconds="<?php echo esc_attr( $r['total_seconds'] ); ?>"><?php echo esc_html( sprintf( '%d:%02d:%02d:%02d', $r['days'], $r['hours'], $r['minutes'], $r['seconds'] ) ); ?></h2><p><?php esc_html_e( 'Server-provided remaining time. Client countdown is informational only.', 'kadad-cms' ); ?></p><dl><dt><?php esc_html_e( 'Subscription code', 'kadad-cms' ); ?></dt><dd><?php echo esc_html( $this->license->masked_code() ); ?></dd><dt><?php esc_html_e( 'License server', 'kadad-cms' ); ?></dt><dd><?php echo esc_html( $l['connection'] ?? '—' ); ?></dd></dl><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="kadad_cms_activate"><?php wp_nonce_field( 'kadad_cms_activate' ); ?><label for="subscription_code"><?php esc_html_e( 'Subscription code', 'kadad-cms' ); ?></label><input id="subscription_code" name="subscription_code" type="text" autocomplete="off" required><button class="button button-primary"><?php esc_html_e( 'Activate / renew', 'kadad-cms' ); ?></button></form></div></div><?php }
	public function settings(): void { register_setting( 'kadad_cms_settings', 'kadad_cms_settings', array( 'sanitize_callback' => array( $this, 'sanitize_settings' ) ) ); }
	public function sanitize_settings( array $input ): array { if ( ! current_user_can( 'manage_options' ) ) return array(); $this->license->save_settings( $input ); return array( 'api_url' => esc_url_raw( $input['api_url'] ?? '' ), 'validation_interval' => max( HOUR_IN_SECONDS, absint( $input['validation_interval'] ?? 0 ) ), 'grace_period' => max( HOUR_IN_SECONDS, absint( $input['grace_period'] ?? 0 ) ), 'debug_logging' => ! empty( $input['debug_logging'] ), 'ui_compact' => ! empty( $input['ui_compact'] ) ); }
	public function settings_page(): void { $l = $this->license->get(); ?><div class="wrap kadad-wrap"><h1><?php esc_html_e( 'Kadad CMS Settings', 'kadad-cms' ); ?></h1><form method="post" action="options.php"><?php settings_fields( 'kadad_cms_settings' ); ?><table class="form-table"><tr><th><label for="api_url"><?php esc_html_e( 'License API server', 'kadad-cms' ); ?></label></th><td><input class="regular-text" id="api_url" name="kadad_cms_settings[api_url]" value="<?php echo esc_attr( $l['api_url'] ); ?>"></td></tr><tr><th><?php esc_html_e( 'Validation interval (seconds)', 'kadad-cms' ); ?></th><td><input name="kadad_cms_settings[validation_interval]" type="number" min="3600" value="<?php echo esc_attr( $l['validation_interval'] ); ?>"></td></tr><tr><th><?php esc_html_e( 'Grace period (seconds)', 'kadad-cms' ); ?></th><td><input name="kadad_cms_settings[grace_period]" type="number" min="3600" value="<?php echo esc_attr( $l['grace_period'] ); ?>"></td></tr><tr><th><?php esc_html_e( 'Debug logging', 'kadad-cms' ); ?></th><td><label><input name="kadad_cms_settings[debug_logging]" type="checkbox" value="1" <?php checked( ! empty( $l['debug_logging'] ) ); ?>> <?php esc_html_e( 'Store redacted license events', 'kadad-cms' ); ?></label></td></tr></table><?php submit_button(); ?></form></div><?php }
}
